project:
  type: website
  pre-render: 
  - example_batch/generate_batch_qmds.R  # generate the templated reports
  render:
  - index.qmd
  - example_batch/batched_reports/*.qmd  # render templated reports
  - example_batch/listing.qmd  # render the listing of reports

website:
  title: "QuartoBatch Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - example_batch/listing.qmd
      - href: https://github.com/7yl4r/quartobatch
        text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false


